name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 25f9bca2-c753-4b69-93ab-761e41107ffc
          heroku_app_name: c2ptrader
          heroku_email: carissa@seattledec.com
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "us"
